micronaut:
  application:
    name: micronautguide
---
#tag::microstream-cache[]
microstream:
  cache:
    headlines:
      key-type: java.time.Month
      value-type: java.util.List
#edn::microstream-cache[]