name: Guides CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-              
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Generate Guides
        run: ./gradlew build          
      - id: outputs
        run: |
          maven_tests=$(ls build/code | grep -e "-maven-" | jq -R -s -c 'split("\n")')
          gradle_tests=$(ls build/code | grep -e "-gradle-" | jq -R -s -c 'split("\n")')
          echo "MAVEN TESTS: $maven_tests"
          echo "GRADLE TESTS: $gradle_tests"
          echo "::set-output name=maven_tests::$maven_tests"
          echo "::set-output name=gradle_tests::$gradle_tests"
    outputs:
      gradle_tests: ${{ steps.build-matrix.outputs.gradle_tests }}
      maven_tests: ${{ steps.build-matrix.outputs.maven_tests }}
  maven-test:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17']
        test_project: ${{ fromJson(needs.build-matrix.outputs.maven_tests) }}
    env:
      JDK_VERSION:  ${{ matrix.java }}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: |
          cd "build/code/$test_project"
          ./mvnw test
  gradle-test:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17']
        test_project: ${{ fromJson(needs.build-matrix.outputs.gradle_tests) }}
    env:
      JDK_VERSION:  ${{ matrix.java }}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: |
          cd "build/code/$test_project"
          ./gradlew test

